version: '2'
services:

  # The Application
  app:
    image: xoco/kendozone:local-1.0.0
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes:
      - laravel:/var/www
    ports:
      - 8080:80

  # The Database
#  database:
#    image: mysql:5.7
#    volumes:
#      - dbdata:/var/lib/mysql
#    environment:
#      - "MYSQL_DATABASE=homestead"
#      - "MYSQL_USER=homestead"
#      - "MYSQL_PASSWORD=secret"
#      - "MYSQL_ROOT_PASSWORD=root"
#    ports:
#        - "33061:3306"
#
volumes:
  laravel:
